use_frameworks!
platform :ios, '10.0'

target 'ProductivitySuite_Example' do
    
    pod 'Alamofire', '~> 4.4.0'
    pod 'Crashlytics'
    pod 'ProductivitySuite', :path => '../'
    pod 'SwiftLint'
    pod 'IGListKit'
#    pod 'Kingfisher', :git => 'https://github.com/onevcat/Kingfisher.git'
    

#    target 'ProductivitySuite_Tests' do
#        inherit! :search_paths
#
##        pod 'Quick'
#
#    end

end
