use_frameworks!

target 'ProductivitySuite_Example' do
    
    pod 'Alamofire'
    pod 'ProductivitySuite', :path => '../'
    
    target 'ProductivitySuite_Tests' do
        inherit! :search_paths
        
        pod 'Quick'
        pod 'Nimble'
#       pod 'FBSnapshotTestCase'
#       pod 'Nimble-Snapshots'

    end
    
end
